apiVersion: security-response-automation.cloud.google.com/v1alpha1
kind: Remediation
metadata:
  name: router
spec:
  parameters:
    etd:
      bad_ip:
      anomalous_iam:
      ssh_brute_force:
    sha:
      public_bucket_acl:
      bucket_policy_only_disabled:
      bigquery_public_dataset:
